Repository derekyeh0426/CPSC_455_Project, pull requests merged in 2021-08, with the labels that each got.

#95 Get all listings by a specific user by user id
  controllers/listing.js
  service/listing.js
Labels: backend

#99 Fix landing layout
  frontend/pfiniture/src/components/landing/DisplayAllFurniture.js
  frontend/pfiniture/src/components/landing/DisplayIndividualFurniture.js
  frontend/pfiniture/src/components/landing/ViewSellerProfile.js
Labels: frontend

#106 Add order shipping address and implement rate and comment on seller
  controllers/user.js
  frontend/pfiniture/src/API/order-api.js
  models/order.js
  models/user.js
  service/order.js
  service/user.js
Labels: backend

#107 implement order query by user id
  .DS_Store
  controllers/order.js
  frontend/pfiniture/src/components/my-account/order-history/Orders.js
  service/order.js
Labels: backend, min req

#110 Fix Order api bug
  service/order.js
Labels: bug, backend

#111 Populate furnitures in order
  models/order.js
  service/order.js
Labels: bug, backend

#117 Implement ratings and comments in User
  controllers/user.js
  models/user.js
  service/user.js
Labels: bug, backend

#118 Add overallRating in User
  models/user.js
  service/user.js
Labels: backend

#119 Return user objects with user name and email
  service/user.js
Labels: backend

#127 Include next steps in the README.md
  README.md
Labels: documentation

#133 Backend cleanup
  controllers/cart.js
  controllers/furniture.js
  controllers/image.js
  controllers/listing.js
  controllers/order.js
  controllers/user.js
  models/order.js
  package-lock.json
  package.json
  service/cart.js
  service/image.js
  service/listing.js
  service/order.js
  service/user.js
Labels: backend

#140 Fix compilation issue
  frontend/pfiniture/package-lock.json
  frontend/pfiniture/src/redux/users/UserLogOutAction.js
  frontend/pfiniture/src/redux/users/userLogOutAction.js
Labels: bug
